spring.application.name=vet

spring.datasource.url=jdbc:postgresql://localhost:5432/veterinaria_db
spring.datasource.username=veterinaria_admin
spring.datasource.password=veterinaria_password
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=TuClaveSecretaEnBase64MuyLargaDeAlMenos256BitsParaHS256AquiVa==
jwt.expiration=86400000